[package]
name = "nix-user-chroot"
version = "1.0.3"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"

[dependencies]
nix = "0.17.*"
tempfile = "3"
rooter = { git = "https://gitlab.com/jD91mZM2/rooter" }
